# Postmodeling Configuration File
  
  project_path: 's3://<url-to-S3-bucket>' # Project path defined in triage with matrices and models
  model_group_id: # List of model_id's [optional if a audition_output_path is given]
        - 40
        - 7
        - 156

  thresholds: # Thresholds for defining positive predictions 
        rank_abs: [5000, 10000, 25000]
        rank_pct: [5, 10, 25]

  baseline_query: | # SQL query for defining a baseline for comparison in plots. It needs a metric and parameter
      SELECT g.model_group_id,
             m.model_id,
             EXTRACT('YEAR' FROM m.evaluation_end_time) AS as_of_date_year,
             m.metric,
             m.parameter,
             m.value,
             m.num_labeled_examples,
             m.num_labeled_above_threshold,
             m.num_positive_labels
       FROM test_results.evaluations m
       LEFT JOIN model_metadata.models g
       USING(model_id)
       WHERE g.model_group_id = 4
             AND metric = 'recall@'
             AND parameter = '10_pct'

  max_depth_error_tree: 5 # For error trees, how depth the decision trees should go?
  n_features_plots: 50 # Number of features for importances
  figsize: [12, 12] # Default size for plots
  fontsize: 20 # Default fontsize for plots

