extension: _body.csv
base_dir: /mnt/data/projects/el_salvador_mined_education/
raw_dir: datos_enviar_UChicago_20152018/
pre_dir: fiveguys/
schema_name: raw.
column_mode_1:
    - 1
    - 4
join_table_string:
    1: [Base_de_Centros]
    4: [riesgo, violencia]
folder_dictionary:
    1: 
        folder: 1._Censo_matricular_-_Centros_educativos
        file_types: 
            - xls 
            - xlsx
        header_split: auto
    2: 
        folder: 2._Censo_matricular_-_Matricula
        file_types: 
            - sav 
            - xlsx
        header_split: 1
    3: 
        folder: 3._Censo_matricular_-_Docentes
        file_types:
            - sav
            - xls 
            - xlsx
        header_split: 1
    4: 
        folder: 4._Monitoreo_a_la_ejecucion_de_programas
        file_types: 
            - xls 
            - xlsx
            - csv
        header_split: 1
    5: 
        folder: 5._Estadistico_de_matricula_mensual
        file_types: 
            - xls 
            - xlsx
        header_split: 1
    6: 
        folder: 6._Registro_de_matricula_oficial
        file_types: 
            - csv
        header_split: 1
    7: 
        folder: 7._Listado_de_centros_educativos_beneficiados_con_programas_sociales
        file_types: 
            - xls 
            - xlsx
        header_split: 4
    8: 
        folder: 8._Listado_de_Centros_educativos_por_indice_de_Priorizacion_de_Centros_educativos
        file_types: 
            - xls 
            - xlsx
        header_split: 4
    9: 
        folder: 9._Censo_matricular_Matricula_Final
        file_types: 
            - xlsx
        header_split: 1
    10: 
        folder: 10._Encuesta_Hogares_PM_2017
        file_types: 
            - csv
        header_split: 1
    11: 
        folder: 11._Social_Progam_Budget
        file_types: 
            - xlsx
        header_split: 1
    12: 
        folder: 12._Graduacion
        file_types: 
            - csv
        header_split: 1
    comma_separated:   
        - 6
        - 12